### ISSUE TITLE
 how to run the codes

### ISSUE THREAD

**Issue by Vlior123** [slingling/MS-HGAT#1]
Could you tell me how to run the codes, there is some wrong. thank you

**Comment by Vlior123** [comment]
Traceback (most recent call last):
  File "run.py", line 217, in <module>
    train_model(model, opt.data_name)
  File "run.py", line 113, in train_model
    model = MSHGAT(opt, dropout = opt.dropout)
  File "/home/bigdata5/xnq/MS-HGAT/HGAT.py", line 135, in __init__
    self.gnn = GraphNN(self.n_node, self.initial_feature, dropout = dropout)
  File "/home/bigdata5/xnq/MS-HGAT/HGAT.py", line 77, in __init__
    self.init_weights()
  File "/home/bigdata5/xnq/MS-HGAT/HGAT.py", line 81, in init_weights
    init.xavier_normal_(self.gnn1.weight)
  File "/home/bigdata5/anaconda3/envs/xnq/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1186, in __getattr__
    type(self).__name__, name))
AttributeError: 'GCNConv' object has no attribute 'weight'
